# 멀티라인으로 방 이름을 적으시면됩니다.

[BotName]
name = 이더

[RoomList]
김영태
#테스트방이야
#봇방
#하트시그널 토론회장
#김자기💖

[APIKey]
path = config/api_key.json

[ChattingRoomSetting]
path = config/chatrooms.json

[EveryMentionDefaultDelayTime]
value = 0.005

[GPT]
maxToken = 1000
defaultModel = gpt-5-nano
answerLengthLimit = 답변은 500자이내로 정리해줘

[GPT_MODEL]
gpt-4o-mini / 80
gpt-5-nano / 70
gpt-5-mini / 90
gpt-5 / 120

[RADAR]
baseUrl = https://awhirl-preimpressive-carina.ngrok-free.dev
apiKeyEnv = GAME_WIKI_API_KEY

[GitHub]
autoUpdate = true
branch = main

[FeatherMonitor]
enabled = true
notification_room = 김영태
# 서버 이름들을 쉼표로 구분하여 입력 (server_paths와 개수가 맞아야 함, 없으면 폴더명 사용)
server_names = 이더서버
# 서버 경로들을 쉼표로 구분하여 입력 (여러 서버 모니터링 가능)
server_paths = C:\Users\이더\AppData\Roaming\.feather\player-server\servers\4f2ad22d-acb5-4137-be6a-5751f2830a25


